# >>>>> Add authors
POST http://localhost:8080/author
Content-Type: application/json

{"email" : "petya@mail.com","name": "Petya"}

###

POST http://localhost:8080/author
Content-Type: application/json

{"email" : "vasya@mail.com","name": "Vasya"}

### >>>>>> Add new Books
POST http://localhost:8080/book
Content-Type: application/json

{
  "title": "Book1",
  "authors": [
    {
      "email": "vasya@mail.com"
    }
  ]
}

###
POST http://localhost:8080/book
Content-Type: application/json

{
  "title": "Book2",
  "authors": [
    {
      "email": "petya@mail.com"
    },
    {
      "email": "vasya@mail.com"
    }
  ]
}

###>>>>>

### Get all books
GET http://localhost:8080/book/all

###

### Get books by author
GET http://localhost:8080/book/author/vasya@mail.com

###

### Get book by id
GET http://localhost:8080/book/2

###

### Delete book by id
DELETE http://localhost:8080/book/2

###
